# Generated by Django 4.2.4 on 2023-11-04 06:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_author_profile_img_alter_post_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_name', models.CharField(max_length=20)),
                ('ad_img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_banner', models.BooleanField(default=True)),
            ],
        ),
    ]
