# Generated by Django 4.2.4 on 2023-11-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_ads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ads',
            new_name='Ad',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='ads_img',
            new_name='ad_img',
        ),
    ]
